/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author komod
 */
public class Fighterpopup extends javax.swing.JPanel {

    /**
     * Creates new form Fighterpopup
     */
    public Fighterpopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnopa = new javax.swing.JRadioButton();
        btnopb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnarch = new javax.swing.JRadioButton();
        btndef = new javax.swing.JRadioButton();
        btnduel = new javax.swing.JRadioButton();
        btngrt = new javax.swing.JRadioButton();
        btnconfirm = new javax.swing.JButton();

        jLabel1.setText("Which Bundle will you choose?");

        buttonGroup1.add(btnopa);
        btnopa.setText("a");
        btnopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnopb);
        btnopb.setText("b");
        btnopb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopbActionPerformed(evt);
            }
        });

        jLabel2.setText("What will your fighting style be?");

        buttonGroup2.add(btnarch);
        btnarch.setText("Archery");
        btnarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarchActionPerformed(evt);
            }
        });

        buttonGroup2.add(btndef);
        btndef.setText("Defencive");
        btndef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndefActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnduel);
        btnduel.setText("Two Weapon FIghting");
        btnduel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnduelActionPerformed(evt);
            }
        });

        buttonGroup2.add(btngrt);
        btngrt.setText("Great Weapon Fighting");
        btngrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrtActionPerformed(evt);
            }
        });

        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btngrt)
                    .addComponent(btnduel)
                    .addComponent(btndef)
                    .addComponent(btnarch)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnopa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnopb))
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnconfirm)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnopa)
                    .addComponent(btnopb))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnarch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnduel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngrt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnconfirm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btngrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngrtActionPerformed

    private void btnduelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnduelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnduelActionPerformed

    private void btndefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndefActionPerformed

    private void btnarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnarchActionPerformed

    private void btnopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnopaActionPerformed

    private void btnopbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnopbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnarch;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JRadioButton btndef;
    private javax.swing.JRadioButton btnduel;
    private javax.swing.JRadioButton btngrt;
    private javax.swing.JRadioButton btnopa;
    private javax.swing.JRadioButton btnopb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
