/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author komod
 */
public class RealFighterPopup extends javax.swing.JDialog {
char selected;
String ftstyle;
    public RealFighterPopup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        selected='?';
        ftstyle=" ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnopa = new javax.swing.JRadioButton();
        btnopb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnarch = new javax.swing.JRadioButton();
        btndef = new javax.swing.JRadioButton();
        btnduel = new javax.swing.JRadioButton();
        btngrt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Which Bundle will you choose?");

        btnopa.setText("a");
        btnopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopaActionPerformed(evt);
            }
        });

        btnopb.setText("b");
        btnopb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopbActionPerformed(evt);
            }
        });

        jLabel2.setText("What will your fighting style be?");

        btnarch.setText("Archery");
        btnarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarchActionPerformed(evt);
            }
        });

        btndef.setText("Defencive");
        btndef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndefActionPerformed(evt);
            }
        });

        btnduel.setText("Two Weapon FIghting");
        btnduel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnduelActionPerformed(evt);
            }
        });

        btngrt.setText("Great Weapon Fighting");
        btngrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btngrt)
                    .addComponent(btnduel)
                    .addComponent(btndef)
                    .addComponent(btnarch)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnopa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnopb))
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnopa)
                    .addComponent(btnopb))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnarch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnduel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btngrt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopaActionPerformed
       selected='a';
    }//GEN-LAST:event_btnopaActionPerformed

    private void btnopbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopbActionPerformed
        selected='b';
    }//GEN-LAST:event_btnopbActionPerformed

    private void btnarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarchActionPerformed
        ftstyle="Archery";
    }//GEN-LAST:event_btnarchActionPerformed

    private void btndefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndefActionPerformed
        ftstyle="Defense";
    }//GEN-LAST:event_btndefActionPerformed

    private void btnduelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnduelActionPerformed
       ftstyle="Two weapon fighting";
    }//GEN-LAST:event_btnduelActionPerformed

    private void btngrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrtActionPerformed
        ftstyle="Great Weapon Fighting";
    }//GEN-LAST:event_btngrtActionPerformed

    public char getSelected() {
        return selected;
    }

    public String getFtstyle() {
        return ftstyle;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealFighterPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealFighterPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealFighterPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealFighterPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RealFighterPopup dialog = new RealFighterPopup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnarch;
    private javax.swing.JRadioButton btndef;
    private javax.swing.JRadioButton btnduel;
    private javax.swing.JRadioButton btngrt;
    private javax.swing.JRadioButton btnopa;
    private javax.swing.JRadioButton btnopb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
